version: '3'

services:
  database:
    container_name: sc-db
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_subscription
      # MYSQL_USER: sandbox_user
      # MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - '3306:3306'
    volumes:
       - './mysql:/var/lib/mysql'
      #- './mysql/dev_subscription.sql:/docker-entrypoint-initdb.d/dev_subscription.sql' # Correction du chemin du fichier SQL


  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    ports:
      - '9000:9000'
    environment:
      PHP_INI_MEMORY_LIMIT: 1024M
    volumes:
      - ./:/var/www/html
    depends_on:
      - database


  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - php
    links:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "9080:80"
    depends_on:
      - database

# git clone https://zakariaamazzal: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@github.com/ohm-energie-it/ohm-souscription-refonte.git
# docker cp dev_subscription.sql sc-db:/var/lib/mysql/dev_subscription.sql
# mysql -u root dev_subscription < /var/lib/mysql/dev_subscription.sql
# wget -O install.sh http://www.aapanel.com/script/install-ubuntu_6.0_en.sh && sudo bash install.sh aapanel